### ISSUE TITLE
Transparency issues with specific font size

### ISSUE THREAD

**Issue by petersanchez** [shiva/st#8]
Sorry, I'm using the LukeSmithxyz port and issues aren't enabled there.

Editing config.h, When I set my font to size 18px, and my alpha variable to "0xcd" I get a core dump when launching st.

    (patched) pjs:thinkpad ~/src/st $ ./st
    free(): invalid next size (normal)
    Aborted (core dumped)
    (patched) pjs:thinkpad ~/src/st $

These are my current config.h changes

```
(patched) pjs:thinkpad ~/src/st $ git diff
diff --git a/config.h b/config.h
index 2794d6c..cf38167 100644
--- a/config.h
+++ b/config.h
@@ -5,7 +5,7 @@
  *
  * font: see http://freedesktop.org/software/fontconfig/fontconfig-user.html
  */
-static char *font = "mono:pixelsize=14:antialias=true:autohint=true";
+static char *font = "mono:pixelsize=18:antialias=true:autohint=true";
 static int borderpx = 2;

 /*
@@ -83,7 +83,7 @@ char *termname = "st-256color";
 unsigned int tabspaces = 8;

 /* bg opacity */
-unsigned int alpha = 0xed;
+unsigned int alpha = 0xcd;

 static const char *colorname[] = {
        "#073642",  /*  0: black    */
@@ -113,9 +113,9 @@ static const char *colorname[] = {
  * Default colors (colorname index)
  * foreground, background, cursor, reverse cursor
  */
-unsigned int defaultfg = 12;
-unsigned int defaultbg = 257;
-static unsigned int defaultcs = 14;
+unsigned int defaultfg = 15;
+unsigned int defaultbg = 256;
+static unsigned int defaultcs = 15;
 static unsigned int defaultrcs = 15;

 /*
(patched) pjs:thinkpad ~/src/st $
```

Strange thing is, this was working just fine before. I noticed i3 wasn't launching my shells and when I manually tried to run them, I'd get the error above. So I updated to the most recent version from Luke's repo, built it, and same thing.

Now if I lower the font size to 16px, it works fine. Just when I put it back to 18px does it crash. Also, if I put the font size to 18px and change the alpha (opacity) variable to "0xff" (so it's black) it works just fine as well.

Any ideas?

**Comment by shiva** [comment]
@petersanchez I don't know the port you are referring to. Can you provide a link to it?

**Comment by petersanchez** [comment]
@shiva The fork is: https://github.com/LukeSmithxyz/st

**Comment by shiva** [comment]
@petersanchez Thanks for the link. It looks like @LukeSmithxyz happened to have done the same thing I did -- create a repo on github to track any patches and changes that I want to maintain for my own "version" of st. 

1. He seems to have opened up issues, and you should raise your request there.

2. Refer to https://st.suckless.org/ for how st is developed and maintained. Neither of these repos (mine and https://github.com/LukeSmithxyz/st ) are authoritative by any means, and as such is not a good idea to fork and continue development. 

I am considering deeply about taking mine down, particularly because having an active repo on github detracts from  st's development from being done close the original source at suckless.org.

I appreciate that you have considered using my copy, but I would highly recommend that you start your own, or better yet, follow as the original authors of st intended -- keep the patches submitted to suckless.org.

**Comment by shiva** [comment]
I am going to keep this repo. After a year of use I believe there is good reason to keep a maintained fork on github. I will periodically maintain sync with the master branch + patches while porting any changes over. 

Since this issue is not applicable on this fork I am closing this specific issue. 

Consider using this for and if you find issues or additional patches to include reach out
